name: release-live
on:
  push:
    tags: ['v*']
jobs:
  release-live:
    uses: muellermarco/sml-cicd-pipeline/.github/workflows/release-live.yml@main
    with:
      slug: salesinsights-snowflake
    secrets: inherit
